// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX5Rc5SMEi0v7DfVUg7IsNmg2Iy1uN55A',
    appId: '1:378528191973:web:14296c75f99e04be814b0c',
    messagingSenderId: '378528191973',
    projectId: 'quickbites-cdd20',
    authDomain: 'quickbites-cdd20.firebaseapp.com',
    storageBucket: 'quickbites-cdd20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYsTBcxU65et1_1lBfS6exX0sFqK3FROA',
    appId: '1:378528191973:android:1981d230fdca9668814b0c',
    messagingSenderId: '378528191973',
    projectId: 'quickbites-cdd20',
    storageBucket: 'quickbites-cdd20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybot_1YmLluv10kG7cQ6pyZUDzj1t09o',
    appId: '1:378528191973:ios:3695b5c727fc8efc814b0c',
    messagingSenderId: '378528191973',
    projectId: 'quickbites-cdd20',
    storageBucket: 'quickbites-cdd20.firebasestorage.app',
    iosBundleId: 'com.example.quickbites',
  );
}
